anguage: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="dca401a0-aa7c-4758-8259-9c2e5dbea0e0"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:k79643812845@gmail.com
    recipients:
      -rail.shamsemukhametov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always