anguage: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="cfb638c6-12bf-4c10-8ae7-623bea016281"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -k79643812845@gmail.com
    on_success: never # default: change
    on_failure: always # default: always